### ISSUE TITLE
Crash/Freeze upon loading a world

### ISSUE THREAD

**Issue by MechanosG** [pcal43/mob-filter#18]
Heya.  Looks like a really cool mod..  was really looking forward to using it's easy syntax.  However, adding it to my modpack then loading an existing world, results in the game freezing up during load.

I wish I could give you a crashlog, but when the game freezes, it fails to create the crashlog, maxing out one of my CPU cores and forces me to end task the game.  However, it does say this in the console.
```
[00:23:29] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.constructor.Constructor.<init>(java.lang.Class)'
	at net.pcal.mobfilter.MFConfig.load(MFConfig.java:17) ~[transformed-mod-mobfilter.i0:0/:?]
	at net.pcal.mobfilter.MFService.loadConfig(MFService.java:115) ~[transformed-mod-mobfilter.i0:0/:?]
	at net.pcal.mobfilter.MFInitializer.lambda$onInitialize$0(MFInitializer.java:19) ~[transformed-mod-mobfilter.i0:0/:?]
	at org.quiltmc.qsl.lifecycle.api.event.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:50) ~[transformed-mod-quilt-lifecycle-events.i0:0/:?]
	at net.minecraft.server.MinecraftServer.handler$fmi000$quilt_lifecycle_events$serverStarting(MinecraftServer.java:3842) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[transformed-mod-minecraft.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Removing Mob Filter allows the modpack to load and run fine again.

This is what's uncommented in my mobfilter.yaml I was testing out -
```
rules:

 - name: No Surface Skeletons
   what: DISALLOW_SPAWN
   when:
     entityId : [minecraft:skeleton]
     dimensionId: ['minecraft:overworld']
     blockY: [0, MAX]
```

MC 1.19.4
Quilt 0.19.1
Mob Filter 0.2.1

**Comment by RetroGamer02** [comment]
Seems like same crash I just had.

24.08 00:37:24 [Server] Server thread/ERROR Encountered an unexpected exception
24.08 00:37:24 [Server] INFO java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.constructor.Constructor.<init>(java.lang.Class)'
24.08 00:37:24 [Server] INFO at net.pcal.mobfilter.MFConfig.load(MFConfig.java:17) ~[mobfilter-0.4.0+1.20.1.jar:?]
24.08 00:37:24 [Server] INFO at net.pcal.mobfilter.MFService.loadConfig(MFService.java:115) ~[mobfilter-0.4.0+1.20.1.jar:?]
24.08 00:37:24 [Server] INFO at net.pcal.mobfilter.MFInitializer.lambda$onInitialize$0(MFInitializer.java:19) ~[mobfilter-0.4.0+1.20.1.jar:?]
24.08 00:37:24 [Server] INFO at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:38) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-21c1963f26916f23.jar:?]
24.08 00:37:24 [Server] INFO at net.minecraft.server.MinecraftServer.handler$zeg000$fabric-lifecycle-events-v1$beforeSetupServer(MinecraftServer.java:2837) ~[server-intermediary.jar:?]
24.08 00:37:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646) ~[server-intermediary.jar:?]
24.08 00:37:24 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
24.08 00:37:24 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]

Fabric Loader 0.14.21 My Server host is 1 version behind not sure if that affects things at all.
Fabric API 0.87.0

**Comment by RetroGamer02** [comment]
Crash Investigated by WORM in the mob-filter discord was found to be caused by ViaFabric. No known workaround though.
