### ISSUE TITLE
failure to start in server mode

### ISSUE THREAD

**Issue by pcal43** [pcal43/mob-filter#6]
hi i like your mod and use it with single player but unable to run it on a fabric server. ive tried it on the last few fabric versions and on 18.1 and 18.2. i specifically tested using just this mod in the mod folder as well adding the last few versions of fabric api. if you have some spare time, would you be able to look into this. i will add my log below this if that helps.

 

[13:05:59] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3

[13:05:59] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3

[13:05:59] [main/INFO]: Loading 36 mods: - fabric 0.48.0+1.18.2 - fabric-api-base 0.4.4+d7c144a860 via fabric - fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric - fabric-biome-api-v1 8.0.3+801ec85b60 via fabric - fabric-command-api-v1 1.1.9+d7c144a860 via fabric - fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric - fabric-containers-v0 0.1.21+d7c144a860 via fabric - fabric-content-registries-v0 3.0.2+d82b939260 via fabric - fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric - fabric-dimensions-v1 2.1.17+2540745460 via fabric - fabric-entity-events-v1 1.4.8+d7c144a860 via fabric - fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric - fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric - fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric - fabric-item-api-v1 1.3.3+691a79b560 via fabric - fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric - fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric - fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric - fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric - fabric-networking-api-v1 1.0.21+d882b91560 via fabric - fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric - fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric - fabric-particles-v1 0.2.12+526dc1ac60 via fabric - fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric - fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric - fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric - fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric - fabric-resource-loader-v0 0.4.18+2de5574560 via fabric - fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric - fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric - fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric - fabricloader 0.13.3 - java 17 - minecraft 1.18.2 - mobfilter 0.0.1 - org_yaml_snakeyaml 1.29 via mobfilter

[13:05:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/x/Desktop/newserver18/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER

[13:05:59] [main/INFO]: Compatibility level set to JAVA_16

[13:06:02] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zca000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

[13:06:03] [main/ERROR]: Failed to start the minecraft server

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mobfilter'! at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?] at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientLifecycleEvents in environment type SERVER at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?] at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at net.pcal.mobfilter.MFInitializer.onInitialize(MFInitializer.java:18) ~[mobfilter-0.0.1.jar:?] at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?] ... 15 more

**Comment by pcal43** [comment]
confirmed
